#!/bin/bash

. config.ini

clean=false
[ "$1" == "clean" ] && clean=true

[ ! -d html ] && cp -r pages html
cd html
[ -d include ] && rm -r include


if ! $clean
then
  svn export https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/error/include
  svn export --force https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/error/contact.html.var
  patch contact.html.var ../patches/norwegian.patch
  patch include/top.html ../patches/base_href.patch
  if $APACHE22_SUPPORT
  then
      patch include/top.html ../patches/apache-2.2-backport.patch
  fi
  echo "<!--#set var=\"BASE_HREF\" value=\"${BASE_HREF}\" -->" > include/config.html
  if $MAKE_THUMBNAIL_VIEWER
  then
      cp ../viewer/* .
      [ -d js ] && rm -r js
      mkdir js
      cd js
      wget https://github.com/niklasvh/html2canvas/releases/download/0.4.1/html2canvas.js
      cp ../../js/* .
  fi
else
  rm contact.html.var
fi

