#!/bin/bash

clean=false
[ "$1" == "clean" ] && clean=true

[ -d include ] && rm -r include

if ! $clean
then
  svn export https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/error/include
  svn export --force https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/error/contact.html.var
  patch contact.html.var norwegian.patch
else
  rm contact.html.var
fi

